package com.miui.aod.widget;

import com.miui.aod.R;
import java.util.HashMap;
import java.util.Map;

public class FrameAnimationManager {
    public static final int[] CLOCK_PANEL_ANIMATION_FIRST_ARRAYS = {R.drawable.aod_clock_panel_animation_first_1, R.drawable.aod_clock_panel_animation_first_2, R.drawable.aod_clock_panel_animation_first_3, R.drawable.aod_clock_panel_animation_first_4, R.drawable.aod_clock_panel_animation_first_5, R.drawable.aod_clock_panel_animation_first_6, R.drawable.aod_clock_panel_animation_first_7, R.drawable.aod_clock_panel_animation_first_8, R.drawable.aod_clock_panel_animation_first_9, R.drawable.aod_clock_panel_animation_first_10, R.drawable.aod_clock_panel_animation_first_11, R.drawable.aod_clock_panel_animation_first_12, R.drawable.aod_clock_panel_animation_first_13, R.drawable.aod_clock_panel_animation_first_14, R.drawable.aod_clock_panel_animation_first_15, R.drawable.aod_clock_panel_animation_first_16, R.drawable.aod_clock_panel_animation_first_17, R.drawable.aod_clock_panel_animation_first_18, R.drawable.aod_clock_panel_animation_first_19, R.drawable.aod_clock_panel_animation_first_20, R.drawable.aod_clock_panel_animation_first_21, R.drawable.aod_clock_panel_animation_first_22, R.drawable.aod_clock_panel_animation_first_23, R.drawable.aod_clock_panel_animation_first_24, R.drawable.aod_clock_panel_animation_first_25, R.drawable.aod_clock_panel_animation_first_26, R.drawable.aod_clock_panel_animation_first_27, R.drawable.aod_clock_panel_animation_first_28, R.drawable.aod_clock_panel_animation_first_29, R.drawable.aod_clock_panel_animation_first_30, R.drawable.aod_clock_panel_animation_first_31, R.drawable.aod_clock_panel_animation_first_32, R.drawable.aod_clock_panel_animation_first_33, R.drawable.aod_clock_panel_animation_first_34, R.drawable.aod_clock_panel_animation_first_35, R.drawable.aod_clock_panel_animation_first_36, R.drawable.aod_clock_panel_animation_first_37, R.drawable.aod_clock_panel_animation_first_38, R.drawable.aod_clock_panel_animation_first_39, R.drawable.aod_clock_panel_animation_first_40, R.drawable.aod_clock_panel_animation_first_41, R.drawable.aod_clock_panel_animation_first_42, R.drawable.aod_clock_panel_animation_first_43, R.drawable.aod_clock_panel_animation_first_44, R.drawable.aod_clock_panel_animation_first_45, R.drawable.aod_clock_panel_animation_first_46, R.drawable.aod_clock_panel_animation_first_47, R.drawable.aod_clock_panel_animation_first_48, R.drawable.aod_clock_panel_animation_first_49, R.drawable.aod_clock_panel_animation_first_50, R.drawable.aod_clock_panel_animation_first_51, R.drawable.aod_clock_panel_animation_first_52, R.drawable.aod_clock_panel_animation_first_53, R.drawable.aod_clock_panel_animation_first_54, R.drawable.aod_clock_panel_animation_first_55, R.drawable.aod_clock_panel_animation_first_56, R.drawable.aod_clock_panel_animation_first_57, R.drawable.aod_clock_panel_animation_first_58, R.drawable.aod_clock_panel_animation_first_59, R.drawable.aod_clock_panel_animation_first_60, R.drawable.aod_clock_panel_animation_first_61};
    public static final int[] CLOCK_PANEL_ANIMATION_SECOND_ARRAYS = {R.drawable.aod_clock_panel_animation_second_1, R.drawable.aod_clock_panel_animation_second_2, R.drawable.aod_clock_panel_animation_second_3, R.drawable.aod_clock_panel_animation_second_4, R.drawable.aod_clock_panel_animation_second_5, R.drawable.aod_clock_panel_animation_second_6, R.drawable.aod_clock_panel_animation_second_7, R.drawable.aod_clock_panel_animation_second_8, R.drawable.aod_clock_panel_animation_second_9, R.drawable.aod_clock_panel_animation_second_10, R.drawable.aod_clock_panel_animation_second_11, R.drawable.aod_clock_panel_animation_second_12, R.drawable.aod_clock_panel_animation_second_13, R.drawable.aod_clock_panel_animation_second_14, R.drawable.aod_clock_panel_animation_second_15, R.drawable.aod_clock_panel_animation_second_16, R.drawable.aod_clock_panel_animation_second_17, R.drawable.aod_clock_panel_animation_second_18, R.drawable.aod_clock_panel_animation_second_19, R.drawable.aod_clock_panel_animation_second_20, R.drawable.aod_clock_panel_animation_second_21, R.drawable.aod_clock_panel_animation_second_22, R.drawable.aod_clock_panel_animation_second_23, R.drawable.aod_clock_panel_animation_second_24, R.drawable.aod_clock_panel_animation_second_25, R.drawable.aod_clock_panel_animation_second_26, R.drawable.aod_clock_panel_animation_second_27, R.drawable.aod_clock_panel_animation_second_28, R.drawable.aod_clock_panel_animation_second_29, R.drawable.aod_clock_panel_animation_second_30, R.drawable.aod_clock_panel_animation_second_31, R.drawable.aod_clock_panel_animation_second_32, R.drawable.aod_clock_panel_animation_second_33, R.drawable.aod_clock_panel_animation_second_34, R.drawable.aod_clock_panel_animation_second_35, R.drawable.aod_clock_panel_animation_second_36, R.drawable.aod_clock_panel_animation_second_37, R.drawable.aod_clock_panel_animation_second_38, R.drawable.aod_clock_panel_animation_second_39, R.drawable.aod_clock_panel_animation_second_40, R.drawable.aod_clock_panel_animation_second_41, R.drawable.aod_clock_panel_animation_second_42, R.drawable.aod_clock_panel_animation_second_43, R.drawable.aod_clock_panel_animation_second_44, R.drawable.aod_clock_panel_animation_second_45, R.drawable.aod_clock_panel_animation_second_46, R.drawable.aod_clock_panel_animation_second_47, R.drawable.aod_clock_panel_animation_second_48, R.drawable.aod_clock_panel_animation_second_49, R.drawable.aod_clock_panel_animation_second_50, R.drawable.aod_clock_panel_animation_second_51, R.drawable.aod_clock_panel_animation_second_52, R.drawable.aod_clock_panel_animation_second_53, R.drawable.aod_clock_panel_animation_second_54, R.drawable.aod_clock_panel_animation_second_55, R.drawable.aod_clock_panel_animation_second_56, R.drawable.aod_clock_panel_animation_second_57, R.drawable.aod_clock_panel_animation_second_58, R.drawable.aod_clock_panel_animation_second_59, R.drawable.aod_clock_panel_animation_second_60, R.drawable.aod_clock_panel_animation_second_61};
    public static final int[] CLOCK_PANEL_ANIMATION_THIRD_ARRAYS = {R.drawable.aod_clock_panel_animation_third_1, R.drawable.aod_clock_panel_animation_third_2, R.drawable.aod_clock_panel_animation_third_3, R.drawable.aod_clock_panel_animation_third_4, R.drawable.aod_clock_panel_animation_third_5, R.drawable.aod_clock_panel_animation_third_6, R.drawable.aod_clock_panel_animation_third_7, R.drawable.aod_clock_panel_animation_third_8, R.drawable.aod_clock_panel_animation_third_9, R.drawable.aod_clock_panel_animation_third_10, R.drawable.aod_clock_panel_animation_third_11, R.drawable.aod_clock_panel_animation_third_12, R.drawable.aod_clock_panel_animation_third_13, R.drawable.aod_clock_panel_animation_third_14, R.drawable.aod_clock_panel_animation_third_15, R.drawable.aod_clock_panel_animation_third_16, R.drawable.aod_clock_panel_animation_third_17, R.drawable.aod_clock_panel_animation_third_18, R.drawable.aod_clock_panel_animation_third_19, R.drawable.aod_clock_panel_animation_third_20, R.drawable.aod_clock_panel_animation_third_21, R.drawable.aod_clock_panel_animation_third_22, R.drawable.aod_clock_panel_animation_third_23, R.drawable.aod_clock_panel_animation_third_24, R.drawable.aod_clock_panel_animation_third_25, R.drawable.aod_clock_panel_animation_third_26, R.drawable.aod_clock_panel_animation_third_27, R.drawable.aod_clock_panel_animation_third_28, R.drawable.aod_clock_panel_animation_third_29, R.drawable.aod_clock_panel_animation_third_30, R.drawable.aod_clock_panel_animation_third_31, R.drawable.aod_clock_panel_animation_third_32, R.drawable.aod_clock_panel_animation_third_33, R.drawable.aod_clock_panel_animation_third_34, R.drawable.aod_clock_panel_animation_third_35, R.drawable.aod_clock_panel_animation_third_36, R.drawable.aod_clock_panel_animation_third_37, R.drawable.aod_clock_panel_animation_third_38, R.drawable.aod_clock_panel_animation_third_39, R.drawable.aod_clock_panel_animation_third_40, R.drawable.aod_clock_panel_animation_third_41, R.drawable.aod_clock_panel_animation_third_42, R.drawable.aod_clock_panel_animation_third_43, R.drawable.aod_clock_panel_animation_third_44, R.drawable.aod_clock_panel_animation_third_45, R.drawable.aod_clock_panel_animation_third_46, R.drawable.aod_clock_panel_animation_third_47, R.drawable.aod_clock_panel_animation_third_48, R.drawable.aod_clock_panel_animation_third_49, R.drawable.aod_clock_panel_animation_third_50, R.drawable.aod_clock_panel_animation_third_51, R.drawable.aod_clock_panel_animation_third_52, R.drawable.aod_clock_panel_animation_third_53, R.drawable.aod_clock_panel_animation_third_54, R.drawable.aod_clock_panel_animation_third_55, R.drawable.aod_clock_panel_animation_third_56, R.drawable.aod_clock_panel_animation_third_57, R.drawable.aod_clock_panel_animation_third_58, R.drawable.aod_clock_panel_animation_third_59, R.drawable.aod_clock_panel_animation_third_60, R.drawable.aod_clock_panel_animation_third_61};
    private static final Map<String, FrameAnimationInfo> sFrameInfoMap = new HashMap();

    public static class FrameAnimationInfo {
        public final int mFps;
        public final int[] mResIdArrays;
        public final int mResIdBg;
        public final int mResIdHour;
        public final int mResIdMin;

        private FrameAnimationInfo(int[] iArr, int i, int i2, int i3, int i4) {
            this.mFps = i2;
            this.mResIdArrays = iArr;
            this.mResIdBg = i;
            this.mResIdHour = i3;
            this.mResIdMin = i4;
        }
    }

    static {
        FrameAnimationInfo frameAnimationInfo = new FrameAnimationInfo(CLOCK_PANEL_ANIMATION_FIRST_ARRAYS, R.drawable.aod_clock_panel_animation_first_small, 30, R.drawable.clock_panel_hour_hand_first, R.drawable.clock_panel_minute_hand_first);
        sFrameInfoMap.put("clock_panel_first", frameAnimationInfo);
        FrameAnimationInfo frameAnimationInfo2 = new FrameAnimationInfo(CLOCK_PANEL_ANIMATION_SECOND_ARRAYS, R.drawable.aod_clock_panel_animation_second_small, 30, R.drawable.clock_panel_hour_hand_second, R.drawable.clock_panel_minute_hand_second);
        sFrameInfoMap.put("clock_panel_second", frameAnimationInfo2);
        FrameAnimationInfo frameAnimationInfo3 = new FrameAnimationInfo(CLOCK_PANEL_ANIMATION_THIRD_ARRAYS, R.drawable.aod_clock_panel_animation_third_small, 30, R.drawable.clock_panel_hour_hand_third, R.drawable.clock_panel_minute_hand_third);
        sFrameInfoMap.put("clock_panel_third", frameAnimationInfo3);
    }

    public static FrameAnimationInfo getFrameAnimationInfoByStyleName(String str) {
        return (FrameAnimationInfo) sFrameInfoMap.get(str);
    }

    public static boolean needFrameAnimation(String str) {
        return sFrameInfoMap.containsKey(str);
    }
}
